### ISSUE TITLE
Move calendar navigation into the taskbar 

### ISSUE THREAD

**Issue by nkfoss** [nkfoss/Z-str#40]
Not sure HOW this would work, but it would be faster than going back to the home page every time.

**Comment by michael-small** [comment]
![Screenshot_20201111-002014](https://user-images.githubusercontent.com/33669563/98776063-e602e680-23b3-11eb-906f-1d6f4233ac66.png)

What if (on mobile) it simply had a down caret to the right of the nav title like how Google Calendar does it? Not as intuitive like the context of "Month v", but those who notice would probably see it as a nice feature. And with the hamburger menu in consideration, I don't think people need the nav title to navigate home.

On desktop you could easily fit it into the nav as its own area. Or... take more inspiration from GCal and have a date picker on a dedicated side bar.

If you get what I'm saying and agree, then I would put in a PR.
